name: Feature request
description: Suggest an improvement
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Describe the current pain point.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What do you want to add/change?
      placeholder: Describe your proposal.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Other options you considered.
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - validation-core
        - validation-compose
        - composeApp
        - siteApp
        - CI/CD
        - docs
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Expected impact
      options:
        - small
        - medium
        - large
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Definition of done
      description: What should be true when this is complete?
      placeholder: Acceptance criteria
